DROP TABLE IF EXISTS sessions CASCADE;
DROP TABLE IF EXISTS subjects CASCADE;
DROP TABLE IF EXISTS students CASCADE;
DROP TABLE IF EXISTS stud_groups CASCADE;
DROP TABLE IF EXISTS chairs CASCADE;
DROP TABLE IF EXISTS faculties CASCADE;